import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  static const String _languageKey = 'app_language';
  late SharedPreferences _prefs;
  String _currentLanguage = 'en';

  // Simple translation map
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_name': 'Tourism App',
      'home': 'Home',
      'favorites': 'Favorites',
      'about': 'About',
      'profile': 'Profile',
      'search': 'Search places...',
      'login': 'Login',
      'register': 'Register',
      'username': 'Username',
      'password': 'Password',
      'email': 'Email',
      'full_name': 'Full Name',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'logout': 'Logout',
      'settings': 'Settings',
      'language': 'Language',
      'categories': 'Categories',
      'see_all': 'See All',
      'all_places': 'All Places',
      'beach': 'Beach',
      'historical': 'Historical',
      'cultural': 'Cultural',
      'religious': 'Religious',
      'suburb': 'Suburb',
      'urban park': 'Urban Park',
      'location': 'Location',
      'description': 'Description',
      'add_to_favorites': 'Add to Favorites',
      'remove_from_favorites': 'Remove from Favorites',
      'about_app': 'About App',
      'developer_team': 'Developer Team',
      'version': 'Version',
      'no_places_found': 'No places found',
      'enter_email': 'Enter your email',
      'enter_full_name': 'Enter your full name',
      'email_required': 'Email is required',
      'invalid_email': 'Please enter a valid email',
      'name_required': 'Name is required',
      'save': 'Save',
      'confirm_logout': 'Confirm Logout',
      'logout_message': 'Are you sure you want to logout?',
      'profile_updated': 'Profile updated successfully',
      'update_failed': 'Failed to update profile',
      'login_failed': 'Login failed. Please check your credentials.',
      'registration_successful': 'Registration successful!',
      'registration_failed': 'Registration failed. Please try again.',
      'dont_have_account': "Don't have an account?",
      'already_have_account': 'Already have an account?',
      'password_required': 'Password is required',
      'password_too_short': 'Password must be at least 6 characters',
      'confirm_password_required': 'Please confirm your password',
      'passwords_dont_match': 'Passwords do not match',
      'login_to_explore': 'Login to explore tourist places',
      'create_account': 'Create Account',
      'start_exploring': 'Start exploring tourist places',
      'support': 'Support',
      'coming_soon': 'Coming Soon!',
      'support_coming_soon':
          'Our support chat feature is under development. Stay tuned for updates!',
      'read_more': 'Read More',
      'welcome': 'Welcome',
      'explore_somalia': 'Explore Somalia',
      'payment_history': 'Payment History',
      'track_booking_payments': 'Track your booking payments',
      'no_payment_history': 'No payment history found',
      'no_payments_made': 'You have not made any payments yet',
      'booking_payments_appear': 'Your booking payments will appear here',
      'make_first_booking': 'Make your first booking to see payment history',
      'retry': 'Retry',
      'payments': 'Payments',
      'please_login_payment_history': 'Please login to view payment history',
      'failed_load_payment_history': 'Failed to load payment history',
      'network_error_check_connection': 'Network error. Please check your connection.',
      'visitors': 'Visitors',
      'time': 'Time',
      'people': 'people',
      'total_amount': 'Total Amount:',
      'paid_amount': 'Paid Amount:',
      'paid_on': 'Paid on',
      'payment_details': 'Payment Details',
      'place': 'Place:',
      'booking_date': 'Booking Date:',
      'time_slot': 'Time Slot:',
      'contact_name': 'Contact Name:',
      'phone': 'Phone:',
      'status': 'Status:',
      'payment_date': 'Payment Date:',
      'transaction_id': 'Transaction ID:',
      'close': 'Close',
      'unknown_place': 'Unknown Place',
      'username_required': 'Username is required',
      'username_cannot_start_number': 'Username cannot start with a number',
      'username_no_symbols': 'Username cannot contain symbols',
      'email_cannot_start_number': 'Email cannot start with a number',
      'email_cannot_start_symbol': 'Email cannot start with a symbol',
      'email_invalid_symbols': 'Email can only contain letters, numbers and @ symbol',
    },
    'so': {
      'app_name': 'App-ka Dalxiiska',
      'home': 'Guriga',
      'favorites': 'La Jecel yahay',
      'about': 'Ku Saabsan',
      'profile': 'Profile',
      'search': 'Raadi meelaha...',
      'login': 'Soo Geli',
      'register': 'Diiwaan geli',
      'username': 'Magaca isticmaalaha',
      'password': 'Lambarka sirta ah',
      'email': 'Email',
      'full_name': 'Magaca Oo Dhammeystiran',
      'submit': 'Dir',
      'cancel': 'Jooji',
      'logout': 'Ka Bax',
      'settings': 'Dejinta',
      'language': 'Luuqadda',
      'categories': 'Qaybaha',
      'see_all': 'Arag Dhammaan',
      'all_places': 'Dhamaan Meelaha',
      'beach': 'Xeebta',
      'historical': 'Taariikhiga',
      'cultural': 'Dhaqanka',
      'religious': 'Diiniga',
      'suburb': 'Degmo',
      'urban park': 'Beer Magaalo',
      'location': 'Goobta',
      'description': 'Sharaxaada',
      'add_to_favorites': 'Ku Dar La Jecel yahay',
      'remove_from_favorites': 'Ka Saar La Jecel yahay',
      'about_app': 'Ku Saabsan App-ka',
      'developer_team': 'Kooxda Horumariyayaasha',
      'version': 'Version',
      'no_places_found': 'Ma jiraan meelo la heli karo',
      'enter_email': 'Geli emailkaaga',
      'enter_full_name': 'Geli magacaaga oo dhammeystiran',
      'email_required': 'Emailka waa lagama maarmaanka ah',
      'invalid_email': 'Fadlan geli email sax ah',
      'name_required': 'Magaca waa lagama maarmaanka ah',
      'save': 'Keydii',
      'confirm_logout': 'Xaqiiji Ka Baxista',
      'logout_message': 'Ma hubtaa inaad ka baxayso?',
      'profile_updated': 'Profile-ka waa la cusboonaysiiyey',
      'update_failed': 'Ma suurto gelin karin cusboonaysiinta profile-ka',
      'login_failed': 'Ma suurto gelin karin galitaanka. Fadlan hubi xogtaaga.',
      'registration_successful': 'Diiwaangelinta waa la sameeyey!',
      'registration_failed':
          'Ma suurto gelin karin diiwaangelinta. Fadlan isku day mar kale.',
      'dont_have_account': 'Ma haysaa akoon?',
      'already_have_account': 'Horey u haysaa akoon?',
      'password_required': 'Lambarka sirta ah waa lagama maarmaanka ah',
      'password_too_short': 'Lambarka sirta ah waa inuu ka yaraadaa 6 xaraf',
      'confirm_password_required': 'Fadlan xaqiiji lambarkaaga sirta ah',
      'passwords_dont_match': 'Lambarrada sirta ah ma isu raacayaan',
      'login_to_explore': 'Gali si aad u baahdo meelaha dalxiiska',
      'create_account': 'Samee Akoon',
      'start_exploring': 'Bilow baahitaanka meelaha dalxiiska',
      'support': 'Caawimaad',
      'coming_soon': 'Dhawaan!',
      'support_coming_soon':
          'Astaamaha caawimaadka waa la horumarinayaa. La soco cusboonaysiinta!',
      'read_more': 'Akhri Wax Dheeraad ah',
      'welcome': 'Ku Soo Dhowow',
      'explore_somalia': 'Baah Soomaaliya',
      'payment_history': 'Taariikhda Lacag Bixinta',
      'track_booking_payments': 'La soco lacag bixintaada dalabka',
      'no_payment_history': 'Ma jiraan taariikhda lacag bixinta',
      'no_payments_made': 'Weli ma aadan lacag bixin',
      'booking_payments_appear': 'Lacag bixintaada dalabka halkan ayay ka muuqan doontaa',
      'make_first_booking': 'Samee dalabkaaga ugu horeeyay si aad u aragto taariikhda lacag bixinta',
      'retry': 'Isku day mar kale',
      'payments': 'Lacag Bixinta',
      'please_login_payment_history': 'Fadlan gali si aad u aragto taariikhda lacag bixinta',
      'failed_load_payment_history': 'Ma suurto gelin karin soo dejinta taariikhda lacag bixinta',
      'network_error_check_connection': 'Khalad shabakad. Fadlan hubi xidhiidhkaaga.',
      'visitors': 'Booqdayaasha',
      'time': 'Waqtiga',
      'people': 'qof',
      'total_amount': 'Wadarta Guud:',
      'paid_amount': 'Lacagta La Bixiyey:',
      'paid_on': 'La bixiyey',
      'payment_details': 'Faahfaahinta Lacag Bixinta',
      'place': 'Goobta:',
      'booking_date': 'Taariikhda Dalabka:',
      'time_slot': 'Waqtiga Xulashada:',
      'contact_name': 'Magaca Xiriirka:',
      'phone': 'Telefoonka:',
      'status': 'Xaalada:',
      'payment_date': 'Taariikhda Lacag Bixinta:',
      'transaction_id': 'Aqoonsiga Macaamilka:',
      'close': 'Xir',
      'unknown_place': 'Goob aan la aqoon',
      'username_required': 'Magaca isticmaalaha waa lagama maarmaanka ah',
      'username_cannot_start_number': 'Magaca isticmaalaha kama bilaaban karo tiro',
      'username_no_symbols': 'Magaca isticmaalaha kama kooban karo calaamado',
      'email_cannot_start_number': 'Email-ku kama bilaaban karo tiro',
      'email_cannot_start_symbol': 'Email-ku kama bilaaban karo calaamad',
      'email_invalid_symbols': 'Email-ku waxaa ka kooban kara xarfo, tiro iyo calaamadda @ oo keliya',
    },
  };

  LanguageProvider() {
    _loadLanguage();
  }

  String get currentLanguage => _currentLanguage;

  Future<void> _loadLanguage() async {
    _prefs = await SharedPreferences.getInstance();
    _currentLanguage = _prefs.getString(_languageKey) ?? 'en';
    notifyListeners();
  }

  Future<void> setLanguage(String language) async {
    if (language != _currentLanguage) {
      _currentLanguage = language;
      await _prefs.setString(_languageKey, language);
      notifyListeners();
    }
  }

  Future<void> toggleLanguage() async {
    String newLanguage = _currentLanguage == 'en' ? 'so' : 'en';
    await setLanguage(newLanguage);
  }

  String getText(String key) {
    return _translations[_currentLanguage]?[key] ?? key;
  }
}
